/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2_felipelin;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author felipelinzhao
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        nombre_t = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        edad_t = new javax.swing.JSpinner();
        jLabel25 = new javax.swing.JLabel();
        rb_1 = new javax.swing.JRadioButton();
        rb_2 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comp_serie = new javax.swing.JTextField();
        comp_colo = new javax.swing.JTextField();
        comp_year = new javax.swing.JSpinner();
        comp_marca_ram = new javax.swing.JTextField();
        comp_marca_dd = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        com_mat_bat = new javax.swing.JTextField();
        comp_horas = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        comp_mat_teclado = new javax.swing.JTextField();
        comp_color_teclado = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        comp_tipo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        comp_tactil = new javax.swing.JComboBox<>();
        comp_tam_ram = new javax.swing.JSpinner();
        comp_tam_dd = new javax.swing.JSpinner();
        comp_velo = new javax.swing.JSpinner();
        comp_nucleos = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        comp_material = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        time_bate = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        time_ram = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        time_dd = new javax.swing.JTextField();
        time_proc = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        time_teclado = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        time_pantalla = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administrador y ensamblaje de computadoras DELL");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jTabbedPane2.setBackground(new java.awt.Color(102, 102, 102));
        jTabbedPane2.setForeground(new java.awt.Color(255, 255, 255));

        jPanel5.setForeground(new java.awt.Color(153, 153, 153));

        jLabel23.setText("Nombre");

        jLabel24.setText("Edad");

        edad_t.setModel(new javax.swing.SpinnerNumberModel(18, 18, 100, 1));

        jLabel25.setText("Genero");

        buttonGroup1.add(rb_1);
        rb_1.setSelected(true);
        rb_1.setText("Masculino");

        buttonGroup1.add(rb_2);
        rb_2.setText("Femenino");

        jButton2.setText("Crear");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombre_t, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edad_t)))
                .addGap(104, 104, 104)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb_1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_2)
                .addContainerGap(297, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre_t, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edad_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_1)
                            .addComponent(rb_2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );

        jTabbedPane2.addTab("Tecnicos", jPanel5);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Numero de Serie");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 26, -1, 22));

        jLabel3.setText("Color");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 67, 96, 24));

        jLabel4.setText("Año");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, 24));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setText("RAM");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 80, 25));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setText("Bateria");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 24, 80, 25));

        jLabel7.setText("Marca");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, 24));

        jLabel8.setText("Tamaño");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));
        jPanel4.add(comp_serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 28, 104, -1));
        jPanel4.add(comp_colo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 103, -1));

        comp_year.setModel(new javax.swing.SpinnerNumberModel(2000, 2000, 2020, 1));
        jPanel4.add(comp_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 112, 103, -1));
        jPanel4.add(comp_marca_ram, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 86, -1));
        jPanel4.add(comp_marca_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 86, -1));

        jLabel9.setText("Marca");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, 24));

        jLabel10.setText("Tamaño");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setText("Disco Duro");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 80, 25));

        jLabel12.setText("Capacidad de horas");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 67, -1, 24));

        jLabel13.setText("Material");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 105, -1, -1));
        jPanel4.add(com_mat_bat, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 103, 86, -1));

        comp_horas.setModel(new javax.swing.SpinnerNumberModel(1, 1, 24, 1));
        jPanel4.add(comp_horas, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 70, 86, -1));

        jLabel14.setText("Color");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, -1, -1));

        jLabel15.setText("Material");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, 24));
        jPanel4.add(comp_mat_teclado, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 86, -1));
        jPanel4.add(comp_color_teclado, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 86, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel16.setText("Teclado");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 80, 25));
        jPanel4.add(comp_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 86, -1));

        jLabel17.setText("Tactil");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 38, 24));

        jLabel18.setText("Tipo");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, -1));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel19.setText("Pantalla");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 80, 25));

        jLabel20.setText("Nucleos");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, -1, 24));

        jLabel21.setText("Velocidad");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, -1, -1));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel22.setText("Procesador");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 80, 25));

        comp_tactil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        jPanel4.add(comp_tactil, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 89, -1));

        comp_tam_ram.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 100.0d, 1.0d));
        jPanel4.add(comp_tam_ram, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 86, -1));

        comp_tam_dd.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 100.0d, 1.0d));
        jPanel4.add(comp_tam_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 86, -1));

        comp_velo.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 100.0d, 1.0d));
        jPanel4.add(comp_velo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, 70, -1));

        comp_nucleos.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        jPanel4.add(comp_nucleos, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 70, -1));

        jButton1.setText("Crear");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, 138, 46));
        jPanel4.add(comp_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 103, -1));

        jLabel26.setText("Material");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, 24));

        jLabel27.setText("Tiempo de ensamble");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));
        jPanel4.add(time_bate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 90, -1));

        jLabel28.setText("Tiempo de ensamble");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));
        jPanel4.add(time_ram, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 90, -1));

        jLabel29.setText("Tiempo de ensamble");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, -1));
        jPanel4.add(time_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 90, -1));
        jPanel4.add(time_proc, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, 80, -1));

        jLabel30.setText("Tiempo de ensamble");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, -1, -1));
        jPanel4.add(time_teclado, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 90, -1));

        jLabel31.setText("Tiempo de ensamble");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, -1));

        jLabel32.setText("Tiempo de ensamble");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));
        jPanel4.add(time_pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 90, -1));

        jTabbedPane2.addTab("Computadoras", jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Crear, Modificar Y Eliminar", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 803, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String ram_marca, dd_marca, bateria_mat, teclado_mat, pantalla_tact = "", pantalla_tipo;
        String serie, material;
        String color, teclado_color;
        int year, bateria_horas, proce_nucleos;
        int time_p,time_r,time_procesador,time_t,time_d,time_b;
        double ram_tam, dd_tam, proce_velocidad;
        AdminCompu ac = new AdminCompu("./Computadoras.ola");

        material = comp_material.getText();
        color = comp_colo.getText();
        serie = comp_serie.getText();
        year = (Integer) comp_year.getValue();
        bateria_horas = (Integer) comp_horas.getValue();
        proce_nucleos = (Integer) comp_nucleos.getValue();
        ram_tam = (Double) comp_tam_ram.getValue();
        dd_tam = (Double) comp_tam_dd.getValue();
        proce_velocidad = (Double) comp_velo.getValue();
        ram_marca = comp_marca_ram.getText();
        dd_marca = comp_marca_dd.getText();
        bateria_mat = com_mat_bat.getText();
        teclado_mat = comp_mat_teclado.getText();
        teclado_color = comp_color_teclado.getText();
        pantalla_tipo = comp_tipo.getText();

        if (comp_tactil.getSelectedIndex() == 0) {
            pantalla_tact = "Tactil";
        } else {
            pantalla_tact = "No Tactil";
        }

        RAM ram = new RAM(ram_tam, ram_marca);
        DiscoDuro dd = new DiscoDuro(dd_marca, dd_tam);
        Bateria bat = new Bateria(bateria_horas, bateria_mat);
        Teclado tec = new Teclado(teclado_mat, teclado_color);
        Pantalla pant = new Pantalla(pantalla_tact, pantalla_tipo);
        Procesador proc = new Procesador(proce_nucleos, proce_velocidad);

        Computadora x = new Computadora(serie, year, color, material, ram, dd, bat, tec, pant, proc);
        ac.cargarArchivo();
        ac.setComputadora(x);
        ac.escribirArchivo();

        JOptionPane.showMessageDialog(this, "Computadora creado exitosamente");

        comp_material.setText("");
        comp_colo.setText("");
        comp_serie.setText("");
        comp_year.setValue(2000);
        comp_horas.setValue(1);
        comp_nucleos.setValue(1);
        comp_tam_ram.setValue(1);
        comp_tam_dd.setValue(1);
        comp_velo.setValue(1);
        comp_marca_ram.setText("");
        comp_marca_dd.setText("");
        com_mat_bat.setText("");
        comp_mat_teclado.setText("");
        comp_color_teclado.setText("");
        comp_tipo.setText("");
        comp_tactil.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        try {
            String nombre, genero;
            int edad;
            nombre = nombre_t.getText();
            edad = (Integer) edad_t.getValue();
            if (rb_1.isSelected()) {
                genero = "Masculino";
            } else {
                genero = "Femenino";
            }
            Tecnicos x = new Tecnicos(edad, nombre, genero);
            AdminTecnico at = new AdminTecnico("./Tecnicos.txt");
            at.cargarArchivo();
            at.setTecnicos(x);
            at.escribirArchivo();

            JOptionPane.showMessageDialog(this, "Agregado con exito un tecnico");

            nombre_t.setText("");
            edad_t.setValue(18);
            rb_1.setSelected(true);
            rb_2.setSelected(false);

        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField com_mat_bat;
    private javax.swing.JTextField comp_colo;
    private javax.swing.JTextField comp_color_teclado;
    private javax.swing.JSpinner comp_horas;
    private javax.swing.JTextField comp_marca_dd;
    private javax.swing.JTextField comp_marca_ram;
    private javax.swing.JTextField comp_mat_teclado;
    private javax.swing.JTextField comp_material;
    private javax.swing.JSpinner comp_nucleos;
    private javax.swing.JTextField comp_serie;
    private javax.swing.JComboBox<String> comp_tactil;
    private javax.swing.JSpinner comp_tam_dd;
    private javax.swing.JSpinner comp_tam_ram;
    private javax.swing.JTextField comp_tipo;
    private javax.swing.JSpinner comp_velo;
    private javax.swing.JSpinner comp_year;
    private javax.swing.JSpinner edad_t;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField nombre_t;
    private javax.swing.JRadioButton rb_1;
    private javax.swing.JRadioButton rb_2;
    private javax.swing.JTextField time_bate;
    private javax.swing.JTextField time_dd;
    private javax.swing.JTextField time_pantalla;
    private javax.swing.JTextField time_proc;
    private javax.swing.JTextField time_ram;
    private javax.swing.JTextField time_teclado;
    // End of variables declaration//GEN-END:variables
}
